/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_rtstvlc_VideoPlayer */

#ifndef _Included_com_example_rtstvlc_VideoPlayer
#define _Included_com_example_rtstvlc_VideoPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_rtstvlc_VideoPlayer
 * Method:    play
 * Signature: (Ljava/lang/String;Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_example_rtstvlc_VideoPlayer_play
  (JNIEnv *, jclass, jstring, jobject);

/*
* Class:     com_example_rtstvlc_VideoPlayer
* Method:    stop
* Signature: ()V
*/
JNIEXPORT void JNICALL Java_com_example_rtstvlc_VideoPlayer_stop
(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
